[package]
name = "typo_ime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objc = "0.2.7"
cocoa = "0.24.0"
libc = "0.2"
